name: Build K-Nel Alioth
on:
  push:
    tags:
      - "C-*"

jobs:
  build:
    name: Build K-Nel Alioth by ${{ github.actor }}
    runs-on: ubuntu-24.04
    steps:

      - name: Set Beijing timezone
        uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: "Asia/Shanghai"

      - name: Set SWAP to 5GiB
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 5

      - name: Clean useless files
        run: |
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          
      - name: Get Tag Name
        id: get-tag
        run: |
          echo "TAG_NAME=$(echo $GITHUB_REF | cut -d'/' -f3)" >> $GITHUB_OUTPUT

      - name: Initialize Compilation Environment
        run: |
          sudo apt-get update
          sudo apt-get install git automake build-essential bc python3 -y
          echo "BUILD_TIME=$(TZ=Asia/Shanghai date "+%Y%m%d%H%M")" >> $GITHUB_ENV
          
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.get-tag.outputs.TAG_NAME }}

      - name: Get Toolchain
        run: |
          git clone -q https://gitlab.com/ThankYouMario/android_prebuilts_clang-standalone.git --depth 1 toolchain/llvm
          git clone https://github.com/KJ-Network/python-2.7.18-prebuilt.git --depth=1 toolchain/python2
          
      - name: Processing submodules
        run: |
          git submodule update --init --remote --rebase --recursive android/Installer
          git submodule update --init --remote --rebase --recursive KernelSU
          sed -i -e '$a\'$'\n''CONFIG_KSU=y\nCONFIG_KSU_MANUAL_HOOK=y\nCONFIG_KSU_SUSFS=y\nCONFIG_KSU_SUSFS_HAS_MAGIC_MOUNT=y\nCONFIG_KSU_SUSFS_SUS_PATH=y\nCONFIG_KSU_SUSFS_SUS_MOUNT=y\nCONFIG_KSU_SUSFS_AUTO_ADD_SUS_KSU_DEFAULT_MOUNT=y\nCONFIG_KSU_SUSFS_AUTO_ADD_SUS_BIND_MOUNT=y\nCONFIG_KSU_SUSFS_SUS_KSTAT=y\nCONFIG_KSU_SUSFS_TRY_UMOUNT=y\nCONFIG_KSU_SUSFS_AUTO_ADD_TRY_UMOUNT_FOR_BIND_MOUNT=y\nCONFIG_KSU_SUSFS_SPOOF_UNAME=y\nCONFIG_KSU_SUSFS_ENABLE_LOG=y\nCONFIG_KSU_SUSFS_HIDE_KSU_SUSFS_SYMBOLS=y\nCONFIG_KSU_SUSFS_OPEN_REDIRECT=y\nCONFIG_KSU_SUSFS_SUS_SU=n' arch/arm64/configs/alioth_k-nel_defconfig
          
      - name: Build Kernel
        run: |
          export LOCALVERSION=${{ steps.get-tag.outputs.TAG_NAME }}
          export KBUILD_BUILD_HOST=Github-Action
          export KBUILD_BUILD_USER=$(echo ${{ github.actor }} | tr A-Z a-z)
          export ARCH="arm64"
          export SUBARCH="arm64"
          export PATH="$GITHUB_WORKSPACE/toolchain/llvm/bin:$GITHUB_WORKSPACE/toolchain/python2/bin:$PATH"
          export LD_LIBRARY_PATH="$GITHUB_WORKSPACE/toolchain/llvm/lib64:$GITHUB_WORKSPACE/toolchain/python2/lib:$LD_LIBRARY_PATH"
          export KBUILD_COMPILER_STRING=$(clang --version | head -n 1 | perl -pe 's/\(http.*?\)//gs' | sed -e 's/  */ /g' -e 's/[[:space:]]*$//')
          export KBUILD_LINKER_STRING=$(ld.lld --version | head -n 1 | perl -pe 's/\(http.*?\)//gs' | sed -e 's/  */ /g' -e 's/[[:space:]]*$//' | sed 's/(compatible with [^)]*)//')
          export CC=clang
          export LLVM=1
          export LLVM_IAS=1
          export CLANG_TRIPLE="aarch64-linux-gnu-"
          export CROSS_COMPILE="aarch64-linux-gnu-"
          make O=out alioth_k-nel_defconfig
          make -j$(nproc --all) O=out

      - name: Pack Kernel
        run: |
          cp out/arch/arm64/boot/Image .
          cp out/arch/arm64/boot/dts/vendor/qcom/*.dtb .
          gzip -k Image Image.gz
          cat Image.gz *.dtb > Image.gz-dtb
          cp Image.gz-dtb android/Installer
          sed -i '/description/ s/$/ Just installed K-Nel Alioth version: ${{ steps.get-tag.outputs.TAG_NAME }}/' android/Installer/module.prop
          
      - name: Upload Kernel Package
        uses: actions/upload-artifact@v4
        with:
          name: K-Nel_Alioth_${{ steps.get-tag.outputs.TAG_NAME }}_AK3&APM_${{ env.BUILD_TIME }}
          path: android/Installer/*
          